# Generated by Django 5.2.8 on 2025-11-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
